// Serves /privacy as a plain static HTML page.
// Using a route handler instead of a page component guarantees Google's
// OAuth verifier can read it — no JavaScript required, pure text/html response.
export async function GET() {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Privacy Policy — Chase Hollow</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0a0a0b; color: #b8b4ac; max-width: 780px; margin: 0 auto; padding: 40px 24px 80px; line-height: 1.7; }
    a { color: #0d6e6e; }
    h1 { color: #f0ede6; font-size: 36px; font-weight: 300; margin-bottom: 8px; }
    h2 { color: #f0ede6; font-size: 18px; font-weight: 500; margin-top: 40px; padding-bottom: 8px; border-bottom: 1px solid #2a2a32; }
    p { margin: 0 0 14px; font-size: 14px; }
    ul { font-size: 14px; padding-left: 20px; margin: 0 0 14px; }
    li { margin-bottom: 6px; }
    strong { color: #f0ede6; }
    .meta { font-size: 12px; color: #6c6a66; margin-bottom: 40px; }
    .contact-box { background: #111114; border: 1px solid #2a2a32; border-radius: 8px; padding: 16px 20px; margin-bottom: 14px; font-size: 13px; }
    .nav { margin-bottom: 32px; }
    .nav a { color: #c9a84c; font-size: 18px; font-weight: 600; text-decoration: none; letter-spacing: 0.08em; }
    .footer { margin-top: 48px; padding-top: 20px; border-top: 1px solid #2a2a32; display: flex; justify-content: space-between; font-size: 12px; }
  </style>
</head>
<body>

<div class="nav"><a href="https://chasehollow.com">CHASE HOLLOW</a></div>

<h1>Privacy Policy</h1>
<div class="meta">Chase Hollow LLC &middot; Idaho, United States &middot; Effective Date: 2026</div>

<p>This Privacy Policy describes how Chase Hollow LLC collects, uses, and shares information when you use our platform at chasehollow.com. By using Chase Hollow, you agree to the practices described here.</p>

<h2>1. Overview</h2>
<p>Chase Hollow LLC ("Chase Hollow," "we," "us," or "our") operates a blockchain-secured trading card marketplace. This policy applies to all users including buyers, sellers, authenticators, and visitors.</p>

<h2>2. Information We Collect</h2>
<p><strong>Account Information:</strong> Email address, username, display name, cryptocurrency wallet address (when connected), and shipping address (for sellers, used to generate shipping labels).</p>
<p><strong>Transaction Data:</strong> Order details, escrow transaction hashes, shipping tracking numbers, authentication inspection records and photos, and dispute records.</p>
<p><strong>Listing Content:</strong> Card details and photos you upload when creating a listing.</p>
<p><strong>Communications:</strong> Messages sent through our in-platform chat and support tickets you submit.</p>
<p><strong>Automatically Collected:</strong> IP address, browser type, device information, pages visited, and referral source including affiliate codes.</p>

<h2>3. How We Use Your Information</h2>
<ul>
  <li>Operate the platform — process transactions, generate shipping labels, authenticate cards, manage escrow, enforce dispute and strike systems</li>
  <li>Communicate with you — send transactional emails (purchase confirmation, shipping updates, auth results, fund releases, disputes, strikes)</li>
  <li>Provide customer support and resolve disputes</li>
  <li>Maintain safety and integrity — detect fraud and enforce our Terms of Service</li>
  <li>Improve the platform through usage analysis</li>
  <li>Creator affiliate attribution — track referral conversions and calculate commissions</li>
  <li>Legal compliance — comply with applicable laws and protect our legal rights</li>
</ul>
<p>We do not sell your personal information to third parties.</p>

<h2>4. Information We Share</h2>
<ul>
  <li><strong>With service providers</strong> — third-party vendors bound by data protection agreements (see Section 5)</li>
  <li><strong>For legal reasons</strong> — if required by law, subpoena, or court order</li>
  <li><strong>With your consent</strong> — for other purposes with your explicit consent</li>
</ul>
<p>Shipping labels are generated by Chase Hollow. Sellers do not receive raw buyer address data. Public profile information (username, seller tier, sales count, reputation scores) is visible to all users by design.</p>

<h2>5. Third-Party Services</h2>
<p>Chase Hollow integrates with the following services, each under its own privacy policy:</p>
<ul>
  <li><strong>Supabase</strong> — database, authentication, and file storage (supabase.com/privacy)</li>
  <li><strong>Privy</strong> — cryptocurrency wallet management (privy.io/privacy-policy)</li>
  <li><strong>Google OAuth</strong> — optional sign-in; Google shares your name and email with us (policies.google.com/privacy)</li>
  <li><strong>Shippo</strong> — shipping label generation (goshippo.com/privacy)</li>
  <li><strong>Resend</strong> — transactional email delivery (resend.com/privacy)</li>
  <li><strong>Alchemy</strong> — blockchain RPC provider for Base network (alchemy.com/policies/privacy)</li>
  <li><strong>Cloudflare</strong> — DDoS protection, WAF, and CDN (cloudflare.com/privacypolicy)</li>
</ul>

<h2>6. Blockchain and Public Data</h2>
<p>Chase Hollow uses smart contracts on the <strong>Base network</strong> (Ethereum Layer 2) to manage escrow. When you participate in a transaction, the following is permanently recorded on the blockchain: your wallet address, transaction amounts in USDC, and escrow events.</p>
<p><strong>Blockchain data is public and permanent.</strong> We cannot delete or modify data recorded on-chain. Anyone can view it on Basescan. Your wallet address, while pseudonymous, may be linkable to your identity.</p>

<h2>7. Cookies and Local Storage</h2>
<ul>
  <li><strong>Authentication cookies</strong> — set by Supabase to maintain your login session</li>
  <li><strong>Local storage</strong> — theme preference (dark/light mode) stored locally, never leaves your device</li>
  <li><strong>Affiliate cookies</strong> — 30-day cookie set when you arrive via a creator referral link</li>
</ul>
<p>We do not use advertising cookies, cross-site tracking, or analytics platforms that share data for advertising.</p>

<h2>8. Data Retention</h2>
<ul>
  <li><strong>Account data</strong> — retained for the life of your account; deletion requests processed within 30 days</li>
  <li><strong>Transaction records</strong> — minimum 7 years for financial recordkeeping</li>
  <li><strong>Authentication photos</strong> — 2 years after transaction completion, then deleted</li>
  <li><strong>Support tickets</strong> — 3 years</li>
  <li><strong>Blockchain data</strong> — permanent, cannot be deleted</li>
</ul>

<h2>9. Security</h2>
<p>We use TLS/HTTPS encryption, row-level database security, server-side key restrictions, Cloudflare WAF protection, and private storage for authentication photos. No method of internet transmission is 100% secure. If you believe your account has been compromised, contact us at <a href="mailto:support@chasehollow.com">support@chasehollow.com</a>.</p>

<h2>10. Your Rights</h2>
<p>You may have the right to access, correct, delete, or port your personal information, and to object to certain uses. Contact us at <a href="mailto:support@chasehollow.com">support@chasehollow.com</a> and we will respond within 30 days. You can update your username, full name, and address at any time from your seller dashboard. Blockchain data cannot be deleted.</p>

<h2>11. Children's Privacy</h2>
<p>Chase Hollow is intended for users <strong>18 years of age or older</strong>. We do not knowingly collect personal information from anyone under 18. Contact us at <a href="mailto:support@chasehollow.com">support@chasehollow.com</a> if you believe a minor has submitted information.</p>

<h2>12. Changes to This Policy</h2>
<p>We may update this Privacy Policy from time to time. When we make material changes, we will update the effective date and notify you by email or platform notification where appropriate. Continued use of Chase Hollow after any update constitutes acceptance of the revised policy.</p>

<h2>13. Contact</h2>
<div class="contact-box">
  <strong>Chase Hollow LLC</strong><br>
  State of Idaho, United States<br>
  Email: <a href="mailto:support@chasehollow.com">support@chasehollow.com</a>
</div>
<p>For the fastest response, use our <a href="https://chasehollow.com/support">contact form</a>.</p>

<div class="footer">
  <a href="/tos">Terms of Service</a>
  <a href="/">Back to Chase Hollow</a>
</div>

</body>
</html>`

  return new Response(html, {
    headers: { 'Content-Type': 'text/html; charset=utf-8' },
  })
}
