// Canonical set lists per game — used in SetCombobox (listing form) and marketplace filter
// Ordered newest-first within each game so the most relevant sets appear at the top

export const SETS_BY_GAME = {
  'Pokémon TCG': [
    // Scarlet & Violet era
    'Prismatic Evolutions',
    'Surging Sparks',
    'Stellar Crown',
    'Shrouded Fable',
    'Twilight Masquerade',
    'Temporal Forces',
    'Paldean Fates',
    'Paradox Rift',
    '151',
    'Obsidian Flames',
    'Paldea Evolved',
    'Scarlet & Violet',
    // Sword & Shield era
    'Crown Zenith',
    'Silver Tempest',
    'Lost Origin',
    'Pokémon GO',
    'Astral Radiance',
    'Brilliant Stars',
    'Fusion Strike',
    'Evolving Skies',
    'Chilling Reign',
    'Battle Styles',
    'Vivid Voltage',
    "Champion's Path",
    'Darkness Ablaze',
    'Rebel Clash',
    'Sword & Shield',
    // Sun & Moon era
    'Cosmic Eclipse',
    'Hidden Fates',
    'Unified Minds',
    'Unbroken Bonds',
    'Detective Pikachu',
    'Team Up',
    'Lost Thunder',
    'Dragon Majesty',
    'Celestial Storm',
    'Forbidden Light',
    'Ultra Prism',
    'Crimson Invasion',
    'Shining Legends',
    'Burning Shadows',
    "Guardians Rising",
    'Sun & Moon',
    // XY era
    'Evolutions',
    'Steam Siege',
    'Fates Collide',
    'Generations',
    'BREAKpoint',
    'BREAKthrough',
    'Ancient Origins',
    'Roaring Skies',
    'Double Crisis',
    'Primal Clash',
    'Phantom Forces',
    'Furious Fists',
    'Flashfire',
    'XY',
    // Black & White era
    'Legendary Treasures',
    'Plasma Blast',
    'Plasma Freeze',
    'Plasma Storm',
    'Boundaries Crossed',
    'Dragon Vault',
    "Dragons Exalted",
    'Dark Explorers',
    'Next Destinies',
    'Noble Victories',
    'Emerging Powers',
    'Black & White',
    // HGSS era
    'Call of Legends',
    'Triumphant',
    'Undaunted',
    'Unleashed',
    'HeartGold & SoulSilver',
    // Platinum / DP era
    'Arceus',
    'Supreme Victors',
    'Rising Rivals',
    'Platinum',
    'Stormfront',
    'Legends Awakened',
    'Majestic Dawn',
    'Great Encounters',
    'Secret Wonders',
    'Mysterious Treasures',
    'Diamond & Pearl',
    // EX era
    'Power Keepers',
    'Dragon Frontiers',
    'Crystal Guardians',
    'Delta Species',
    'Unseen Forces',
    'Emerald',
    'Deoxys',
    'Team Rocket Returns',
    'FireRed & LeafGreen',
    'Hidden Legends',
    'Team Magma vs. Team Aqua',
    'Dragon',
    'Sandstorm',
    'Ruby & Sapphire',
    // Vintage
    'Legendary Collection',
    'Neo Destiny',
    'Neo Revelation',
    'Neo Discovery',
    'Neo Genesis',
    'Gym Challenge',
    'Gym Heroes',
    'Team Rocket',
    'Fossil',
    'Jungle',
    'Base Set',
    'Base Set 2',
    'Base Set Shadowless',
    'Base Set 1st Edition',
  ],

  'Magic: The Gathering': [
    // Recent
    'Foundations',
    'Duskmourn: House of Horror',
    'Bloomburrow',
    'Modern Horizons 3',
    'Outlaws of Thunder Junction',
    'Murders at Karlov Manor',
    'Lost Caverns of Ixalan',
    'Wilds of Eldraine',
    'March of the Machine: The Aftermath',
    'March of the Machine',
    'Phyrexia: All Will Be One',
    'The Brothers\' War',
    'Dominaria United',
    'Streets of New Capenna',
    'Kamigawa: Neon Dynasty',
    'Innistrad: Crimson Vow',
    'Innistrad: Midnight Hunt',
    'Adventures in the Forgotten Realms',
    'Strixhaven: School of Mages',
    'Kaldheim',
    'Zendikar Rising',
    'Core Set 2021',
    // Remastered / Premium
    'The Lord of the Rings: Tales of Middle-earth',
    'Commander Masters',
    'Ravnica Remastered',
    'Double Masters 2022',
    "Commander Legends: Battle for Baldur's Gate",
    'Jumpstart 2022',
    'Modern Horizons 2',
    'Time Spiral Remastered',
    'Kaladesh Remastered',
    'Zendikar Rising Expeditions',
    // Classic recent
    'Throne of Eldraine',
    'Theros Beyond Death',
    'Ikoria: Lair of Behemoths',
    'Core Set 2020',
    'War of the Spark',
    'Ravnica Allegiance',
    'Guilds of Ravnica',
    'Core Set 2019',
    'Dominaria',
    'Rivals of Ixalan',
    'Ixalan',
    'Hour of Devastation',
    'Amonkhet',
    'Aether Revolt',
    'Kaladesh',
    'Eldritch Moon',
    'Shadows over Innistrad',
    'Oath of the Gatewatch',
    'Battle for Zendikar',
    'Magic Origins',
    'Dragons of Tarkir',
    'Fate Reforged',
    'Khans of Tarkir',
    'Magic 2015',
    'Journey into Nyx',
    'Born of the Gods',
    'Theros',
    'Magic 2014',
    "Dragon's Maze",
    'Gatecrash',
    'Return to Ravnica',
    'Magic 2013',
    'Avacyn Restored',
    'Dark Ascension',
    'Innistrad',
    'Magic 2012',
    'New Phyrexia',
    'Mirrodin Besieged',
    'Scars of Mirrodin',
    'Magic 2011',
    'Rise of the Eldrazi',
    'Worldwake',
    'Zendikar',
    'Magic 2010',
    'Alara Reborn',
    'Conflux',
    'Shards of Alara',
    // Masters sets
    'Ultimate Masters',
    'Iconic Masters',
    'Eternal Masters',
    'Masters 25',
    'Modern Masters 2017',
    'Modern Masters 2015',
    'Modern Masters',
    // Vintage
    'Lorwyn',
    'Time Spiral',
    'Ravnica: City of Guilds',
    "Champions of Kamigawa",
    'Mirrodin',
    'Onslaught',
    'Invasion',
    "Mercadian Masques",
    "Urza's Saga",
    "Tempest",
    'Ice Age',
    'Revised Edition (3rd Edition)',
    'Unlimited Edition (2nd Edition)',
    'Beta Edition (2nd Edition)',
    'Alpha Edition (1st Edition)',
  ],

  'One Piece TCG': [
    // Booster Sets (English)
    'OP10: Royal Blood',
    'OP09: The Four Emperors',
    'OP08: Two Legends',
    'OP07: 500 Years in the Future',
    'OP06: Wings of the Captain',
    'OP05: Awakening of the New Era',
    'OP04: Kingdoms of Intrigue',
    'OP03: Pillars of Strength',
    'OP02: Paramount War',
    'OP01: Romance Dawn',
    // Extra / Premium
    'Premium Booster -THE BEST-',
    'Extra Booster -Memorial Collection-',
    // Starter Decks
    'ST21: Purple — Charlotte Katakuri',
    'ST20: Black — Monkey D. Garp',
    'ST19: Blue — Smoker',
    'ST18: Yellow — Charlotte Linlin',
    'ST17: Purple — Donquixote Doflamingo',
    'ST16: Green — Uta',
    'ST15: Red — Edward Newgate',
    'ST14: 3D2Y',
    'ST13: The Three Brothers',
    'ST12: Zoro & Sanji',
    'ST11: Uta',
    'ST10: Royal Pirates',
    'ST09: Yamato',
    'ST08: Monkey D. Luffy',
    'ST07: Big Mom Pirates',
    'ST06: Absolute Justice',
    'ST05: Film Edition',
    'ST04: Animal Kingdom Pirates',
    'ST03: The Seven Warlords of the Sea',
    'ST02: Worst Generation',
    'ST01: Straw Hat Crew',
  ],

  'Yu-Gi-Oh!': [],
  'Sports Cards': [],
  'Other': [],
}

// Map marketplace category IDs → game key (for filtering sets in the sidebar)
export const SETS_BY_CATEGORY = {
  pokemon:  SETS_BY_GAME['Pokémon TCG'],
  mtg:      SETS_BY_GAME['Magic: The Gathering'],
  onepiece: SETS_BY_GAME['One Piece TCG'],
  yugioh:   SETS_BY_GAME['Yu-Gi-Oh!'],
  sports:   SETS_BY_GAME['Sports Cards'],
}
